# Generated by Django 6.0.3 on 2026-04-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_withdrawalblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_real_name',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
