# Generated by Django 5.2.12 on 2026-05-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
