# Generated by Django 5.2.12 on 2026-05-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_image_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('IMAGE', 'IMAGE'), ('SYSTEM', 'SYSTEM')], default='TEXT', max_length=20),
        ),
    ]
