# Generated by Django 6.0.3 on 2026-03-23 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=80)),
                ('depart_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('depart_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrive_name', models.CharField(max_length=80)),
                ('arrive_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('arrive_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('depart_time', models.DateTimeField()),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)])),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('FULL', 'FULL'), ('CANCELED', 'CANCELED'), ('CLOSED', 'CLOSED'), ('COMPLETED', 'COMPLETED')], default='OPEN', max_length=20)),
                ('estimated_fare', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_created', to=settings.AUTH_USER_MODEL)),
                ('leader_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_led', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'LEADER'), ('MEMBER', 'MEMBER')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('JOINED', 'JOINED'), ('LEFT', 'LEFT'), ('KICKED', 'KICKED')], default='JOINED', max_length=20)),
                ('seat_position', models.CharField(choices=[('FRONT_PASSENGER', '앞좌석'), ('REAR_LEFT', '뒷좌석 왼쪽'), ('REAR_RIGHT', '뒷좌석 오른쪽'), ('REAR_MIDDLE', '뒷좌석 가운데')], max_length=30)),
                ('confirmed_departure', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participants', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 2), ('capacity__lte', 4)), name='trips_trip_capacity_range'),
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(fields=('trip', 'user'), name='unique_trip_participant'),
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(fields=('trip', 'seat_position'), name='unique_trip_seat_position'),
        ),
    ]
