# Generated by Django 5.2.12 on 2026-05-10 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tripparticipant',
            name='unique_trip_seat_position',
        ),
        migrations.AlterField(
            model_name='tripparticipant',
            name='seat_position',
            field=models.CharField(blank=True, choices=[('FRONT_PASSENGER', '앞좌석'), ('REAR_LEFT', '뒷좌석 왼쪽'), ('REAR_RIGHT', '뒷좌석 오른쪽'), ('REAR_MIDDLE', '뒷좌석 가운데')], max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='tripparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('seat_position__isnull', False), ('status', 'JOINED')), fields=('trip', 'seat_position'), name='unique_joined_trip_seat_position'),
        ),
    ]
