# Generated by Django 6.0.3 on 2026-04-29 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='provider',
            field=models.CharField(choices=[('KAKAOPAY', 'KAKAOPAY'), ('TOSS', 'TOSS'), ('OTHER', 'OTHER')], default='KAKAOPAY', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_arrival_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_departure_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_ride_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('NEEDS_REVIEW', 'NEEDS_REVIEW')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='settlement',
            name='link_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('REQUEST', 'REQUEST'), ('LINK_OPENED', 'LINK_OPENED'), ('PAID_SELF', 'PAID_SELF'), ('CONFIRMED', 'CONFIRMED'), ('DISPUTED', 'DISPUTED'), ('OVERDUE', 'OVERDUE'), ('CANCELED', 'CANCELED')], default='REQUEST', max_length=20),
        ),
    ]
